### ISSUE TITLE
Compat Issue with Blocks for Builders and Modern Fix, Render Issue

### ISSUE THREAD

**Issue by suerion** [disjoint-account/BlocksForBuilders#1]
Hey, i had an issue with your mod. When i add your mod to my huge modpack, it does mess with other Mods like Oh The Biomes We've gone and other world gen mods....

But had no Issues on Console ore something
Here without your mod ->
![2024-11-22_19 23 12](https://github.com/user-attachments/assets/92ea19cd-c78c-4073-adc6-0586721e1f23)

with your mod
![2024-11-22_19 30 11](https://github.com/user-attachments/assets/83200c3b-3a3b-433a-887c-bd2958f02ca4)

**Comment by disjoint-account** [comment]
Yeah that does not look ideal, cheers for letting me know. Probably something I need to change to do with terrablender; I'll have a look if I get the chance tomorrow and try get it fixed for you.

**Comment by disjoint-account** [comment]
Just did some quick testing and I can't seem to replicate this using any combo of BFB, OTBWB, and BOP. Would you be able to post your full mods list and let me know the version of BFB you're using, and as much info as you can on the problem - is the issue everywhere or localised to specific biomes? What are those white blocks supposed to be; what do they show up as if you pick block them?

**Comment by suerion** [comment]
sorry, i had forgotten the latest.log

https://mclo.gs/1vL7Fz3

**Comment by disjoint-account** [comment]
683 mods oof. BFB is disabled in that log, would you be able to get one where it's not so I can see what loads in? And you're sure it's BFB? ie if you run just the other 682, the issue doesn't occur?

**Comment by suerion** [comment]
i will start later the server or tomorow, i will give you an log ;)

And yes, it occurs only with BFB

**Comment by suerion** [comment]
https://mclo.gs/l2Mhwad

**Comment by disjoint-account** [comment]
I've been trying various combinations of the mods you mentioned but I can't seem to replicate the issue. Trying combinations of all 600+ mods to work out what the conflict is isn't really feasible so without more information there's not much I can do unfortunately. Does the issue occur in biomes everywhere or is it specific biomes, from a specific mod?

**Comment by suerion** [comment]
Sorry, i had not the time yet to answer.

I will try to debug more of this issue, it is a little bit weired, i think it is an Render issue, after disabling the mod, it shows all normal, but only with your mod.

don't know yet what it is the issue.

**Comment by disjoint-account** [comment]
No worries. Yeah, it does look like a rendering issue. Definitely happy to make changes/look into it more if you can work out what the conflict is, just hard to do anything from my end atm since I can't reproduce it.

**Comment by suerion** [comment]
Had not found the issuer right now

**Comment by disjoint-account** [comment]
Do you mean you haven't been seeing the problem occur, or that you just haven't found what the conflict is? If it's the former, I'll close this issue and you can reopen it/make a new one if it ever crops up again

**Comment by suerion** [comment]
I had not found the compat yet, had done partial testing also, don't get the hint. 

Starts allways with complete modpack

**Comment by vadr99** [comment]
Hiya.
Having almost the same issue with my mod pack (only 47 mods) at the moment. [Edit:] Using 1.21.1
Weirdly only while its loaded on a server though, it works 100% as it should in the exact same world loaded as a single player world. I've attached a screenshot of what is happening. 
Trees from Biomes of Plenty wont load correctly and trees from your mod load with floating indestructible pots with saplings. Can also not plant saplings from any modded trees as they turn straight into a leaf block.
Thanks, vadr.
![clientside](https://github.com/user-attachments/assets/461ba5b8-cd75-4182-a607-3347fb5bfb92)
![serverside](https://github.com/user-attachments/assets/30903701-8928-44df-9eb2-d2fa6b3580e5)

**Comment by disjoint-account** [comment]
This is super helpful, thank you! Never occurred to me that it could be a server-only thing, and very useful to know it seems to be with a specific mod. Looks super bizarre, absolutely no idea what could be causing it, but I'll try figure it out and get a fix sorted for you.

**Comment by disjoint-account** [comment]
Having just done some testing with BFB and BOP, I couldn't replicate the issue in your screenshot, even while hosting the world on a server. So I'm guessing either I'm using newer versions of mods where something small changed, or the conflict is coming from another mod. Would you be able to link your full modpack so I can test further?
Here are the mods and versions I had installed:
- BFB v3.2.0
- Biomes O'Plenty v21.1.0.7
- GlitchCore v2.1.0.0
- Terrablender v4.1.0.8
- Fabric API v0.114.0

**Comment by vadr99** [comment]
Sorry, in the meantime I think I've ruled out your mod as being the issue but I'm not 100% sure and I'm still having the same problem regarding the trees from this mod and I don't know what the issue is.
I also might mention that this issue happened AS SOON as the server started and was not caused by my adding/removing mods or messing with server files.
The mods I'm using are:

1. Accessories 1.1.0-beta.21
2. Architectury API 13.0.8
3. Backpacked 1.21.1-3.0.0-beta.10
4. Balm 21.0.23
5. Better Archeology 1.3.1 (added after bug was noticed)
6. Biolith 3.0.0
7. Biomes O' Plenty 21.1.0.7
8. Blocks For Builders 3.2.0
9. Call Your Cat v1.1.1
10. Cat Loaf 1.1.2
11. Cat Jam 1.3.1
12. Chest Tracker 2.6.5
13. Collective 7.87
14. Continuity 3.0.0
15. Cristel Lib 1.2.8
16. Death Finder v21.1.0
17. Dungeons and Taverns v4.4.4
18. Dusks Biomes 1.2.0
19. Fabric API 0.114.0
20. Fabric Language Kotlin 1.13.0
21. FerriteCore 7.0.2
22. Forge Config API Port v21.1.3
23. Framework 0.9.4
24. GlitchCore 2.1.0.0
25. Infinite Trading 4.5 (added after bug was noticed)
26. Iris Shaders 1.8.1 (added after bug was noticed)
27. Jade 15.9.2 (added after bug was noticed)
28. JamLib 1.2.2
29. Just Enough Items 19.21.0.247 (added after bug was noticed)
30. Lithium 0.14.3
31. ModernFix 5.20.0
32. Nyan Cat Loading 2.0
33. OptiFine_1.21.1_HD_U_J1.jar
34. owo-lib 0.12.15
35. Polymer 0.9.18
36. Puzzles Lib v21.1.25
37. Resourceful Config 3.0.8
38. Rightclickharvest 4.4.4 (this is the only one that gives me a chat message that it isnt installed but i havent bothered to fix it since i havent done any farming yet)
39. Sodium 0.6.5
40. Tectonic 2.4.1a
41. Terrablender 4.1.0.8
42. Towns and Towers 1.13.2
43. Trade Cycling 1.0.15 (added after bug was noticed)
44. Universal Graves 3.4.4 (added after bug was noticed)
45. Waystones 21.1.5 (added after bug was noticed)
46. Xaeros Minimap 24.7.1 (added after bug was noticed)
47. YetAnotherConfigLib 3.6.2

That's all :)

**Comment by disjoint-account** [comment]
It feels more like something that'd be caused by some kind of general worldgen/config mod than mine specifically, since I don't see how BFB would actually change the blocks making up a tree from a totally unrelated mod. I'm happy to keep testing in case it is mine but my gut feeling is that there's something in a more universal mod somewhere that's just setting things to leaves for some reason. I have the fallen leaves in the #leaves block tag, which is the only thing I can think of for why their models are randomly changing to leaves, but the BOP tree changing I have no clue about, and the saplings showing up under the yellow birch seems more like my trees are trying to mimic the BOP ones for some reason?

I'm a bit busy today but I can download all those mods and play around with them tomorrow to try and find out what's causing the conflict. Even if it's not BFB, I might be able to add something to at least resolve the incompatibility with BFB specifically.

**Comment by vadr99** [comment]
Omg I feel so silly for not checking world gen/optimisation mods I've just checked and it seems to be the mod called ModernFix 5.20.0. I removed it server side only and it stopped my issue, sorry if I've wasted any of your time here but I think I may have found an incompatible mod which I hope is useful information for you. Weird how it seems to have affected BOP and BFB differently though, and only on trees.
Thank you so much for your time and the great mod :)
vadr.

**Comment by disjoint-account** [comment]
No worries at all! Glad it's sorted! It's possible I'd maybe be able to fix the specific BFB incompatibility from my end but given this is clearly an issue it has with other mods too I'm more inclined to just put something in my Modrinth description mentioning the incompatibility and hope they fix it on their end lol.

As for suerion's issue, I see ModernFix in your modlist so I guess try taking that out if you haven't already. I'll leave the issue open for now in case you figure anything out with your testing but given I can't reproduce it and the number of mods isn't really tenable for testing my hands are fairly tied. Given that BFB literally wasn't enabled in your first log, where the screenshot was from, I'm inclined to write the root cause of this off as being another mod.

**Comment by suerion** [comment]
Will try disable modern fix, then come pack with an info. Could be an issue of the dynamic ressource. Will test a little bit here

**Comment by suerion** [comment]
Something went on my side wrong, i could not test without Modern Fix, but i had added Worldedit. -> Now i get this error ->

```
[23:14:54 ERROR] [Server thread]: [EventBus] Could not dispatch event: com.sk89q.worldedit.event.platform.PlatformReadyEvent@30bdb460 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at knot/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.fabric.FabricWorldEdit.onStartServer(FabricWorldEdit.java:303) ~[worldedit-mod-7.3.8.jar:?]
        at knot/net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.5.0+01d9a51c19-d79236b315b9dd73.jar:?]
        at knot/net.minecraft.server.MinecraftServer.handler$dpo001$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:14143) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:668) ~[server-intermediary.jar:?]
        at knot/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.IllegalStateException: BlockState blocksforbuilders:pumpkin_pie[chomps=0] is using the same block ID (0) as BlockState minecraft:air
        at knot/com.google.common.base.Preconditions.checkState(Preconditions.java:854) ~[guava-32.1.2-jre.jar:?]
        at knot/com.sk89q.worldedit.internal.block.BlockStateIdAccess.register(BlockStateIdAccess.java:92) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.extension.platform.Capability$4.ready(Capability.java:99) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.extension.platform.PlatformManager.lambda$handleNewPlatformReady$0(PlatformManager.java:342) ~[worldedit-mod-7.3.8.jar:?]
        at java.base/java.util.Map.forEach(Map.java:733) ~[?:?]
        at knot/com.sk89q.worldedit.extension.platform.PlatformManager.handleNewPlatformReady(PlatformManager.java:342) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[worldedit-mod-7.3.8.jar:?]
        at knot/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-mod-7.3.8.jar:?]
        ... 8 more
```

**Comment by disjoint-account** [comment]
Hmm, I'll have a look at that and see if I can figure out a fix. I guess in the meantime remove WorldEdit and test without modernFix

**Comment by disjoint-account** [comment]
Testing with BFB and 3.2.0 and WorldEdit v7.3.8, I can't replicate this crash. Can you post your full log?

**Comment by suerion** [comment]
https://mclo.gs/KK2MoDO

Here is the full log, recipes and Item regystries error are not all fixed yed, but soon

**Comment by disjoint-account** [comment]
I can't reproduce this, despite my best efforts. Minecraft hasn't used numerical Block IDs for years; as far as I understand it it's just a WorldEdit thing. As far as I can tell, the Pumpkin Pie block isn't set to that by default, so I'm willing to bet that similar to vadr's ModernFix issue, there's some sort of expansive optimisation mod or whatever that's changing things. Given BFB's being disabled when the original issue occurred, I'd wager that's the case there too. The presence of BFB might lead to an issue, but the root cause is coming from somewhere else, since BFB's code wasn't even running. 


If the incompatibility were known, I could potentially look into fixing it from my end, but with 683+ mods, testing just isn't feasible for me. All I can really do is suggest just dropping BFB from your pack (if simply removing it resolves whatever the issues are), or looking for the incompatibility on your own and then remove whatever the root cause mod is. Good luck if you opt for the latter, and feel free to let me know if you find it, but I'm going to close this issue now since, as I can't reproduce any of this, my hands are tied.

**Comment by suerion** [comment]
So, now i had found the issue on BFB with the false Render issue,

i had yet again, after you gave me the hint with Modern fix, the issue, without modernfix, it works fine,

i'm now looking what Problem from Modern fix give me this render issue 

Had before an other issue to fix, now it work and i could test again, (Remote server errors, not minecraft) @disjoint-account

**Comment by suerion** [comment]
Could you open the Issue again please

**Comment by suerion** [comment]
With Modernfix, 

![Image](https://github.com/user-attachments/assets/d6a4a949-ce09-48d2-a8bd-2067f033f6b9)

With ModernFix and disabled dynamic Ressources 

![Image](https://github.com/user-attachments/assets/fd16186f-d03b-4279-8725-96199624682d)

without ModernFix

![Image](https://github.com/user-attachments/assets/73b07830-b6f7-4c1c-9866-daf04b741367)

**Comment by disjoint-account** [comment]
We know from vadr's case that this is a wider issue with ModernFix; it causes issues with more mods than just BFB. The issue is on their end, not mine. I'm glad you found the problem, but either you'll have to drop ModernFix or BFB, or go take the issue up with ModernFix. I don't plan on doing anything on my end since it's predominantly a ModernFix issue.

**Comment by suerion** [comment]
Okey

```
mixin.feature.spark_profile_launch=true
mixin.feature.direct_stack_trace=true
mixin.perf.dynamic_resources=true
mixin.perf.dynamic_entity_renderers=true
mixin.perf.faster_item_rendering=true
mixin.perf.state_definition_construct=true
```

had tried also the to fix with some renderer settings, but not get the right informations yet

Will go to ModernFix @vadr99 did you open an issue there?

![Image](https://github.com/user-attachments/assets/24b332f1-f370-40b5-800d-9c1641e15592)

**Comment by disjoint-account** [comment]
Looking at ModernFix's Modrinth page, they actually mention that Dynamic Resource is known to cause model loading issues and as such is disabled by default, so I guess it's known on their end and they're not looking to do anything about it either. I guess just decided if you'd rather keep Dynamic Resource or BFB.

**Comment by suerion** [comment]
> Looking at ModernFix's Modrinth page, they actually mention that Dynamic Resource is known to cause model loading issues and as such is disabled by default, so I guess it's known on their end and they're not looking to do anything about it either. I guess just decided if you'd rather keep Dynamic Resource or BFB.

the problem is not on Dynamic Resources, i had disabled the option also, it is an other issue, had tried also the versions 5.19.0 and 5.19.6, in all mods, with dynamic resources false, it has also this issue

**Comment by disjoint-account** [comment]
Ah I see. Well, good luck figuring it out.
